### PR TITLE
Modify the area computation to use inside polygon point

### PR DESCRIPTION
**Pull request by bernie-simon**
The previous area computation assumed that the polygon was smaller
 than a hemisphere (2 pi) and converted the computed area to a negative
 number when larger. The new code looks at the polygon vertices and if
 they are ordered clockwise with respect to the inside point, the area
 is poitive and if they are ordered counter-clockwise, the area is
 negative. This change allows all sizes of polygon to be handled, up to
 4 pi. To support this, a new method, is_clockwise has been added to
 _SingleSphericalPolygon.
    
 I also added auto_close and auto_orient parameters when creating new
 polygon objects. Both are false by default. If auto_close is set to
True, the first point in the polygon is added as the last, closing the
 polygon. If auto_orient is True and the polygon vertices are ordered
 counter-clockwise, the list of vertices is reversed to orient them
 clockwise.
    
 Testing revealed that the computation of the internal point was
 incorrect for the special cose of a triangle, so I rewote that code. I
 also modified the general case to choose the vertex with the sharpest angle.

### CODE REVIEW

**Comment by bernie-simon** [comment]
Rejected because of merge conflicts. Will resolve them and retry

**Comment by pllim** [comment]
Did you try rebasing?

**Comment by bernie-simon** [comment]
On Jun 23, 2016, at 9:47 AM, P. L. Lim <notifications@github.com> wrote:

> Did you try rebasing?

No, but I seem to have resolved the problem somehow or another.

**Comment by pllim** [comment]
Magic!

**Pull request closed without merging**
