### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by jhunkeler**
Fixes miniconda's `PATH` definition to point to the correct location.

### CODE REVIEW

**Comment by jhunkeler** [comment]
This is safe to merge. The travis-ci errors are unrelated to this.

**Comment by pllim** [comment]
Actually, `sphere` already have Astropy package template. So, the more appropriate fix is to use the one in the latest [Astropy template](https://github.com/astropy/package-template).

**Comment by cdeil** [comment]
@bernie-simon @astrofrog - Is this PR superseded by #84? Close?

**Comment by bernie-simon** [comment]
No, I still need to address this. Will get back to it after I finish a problem with asdf.

**Pull request closed without merging**
