### PR TITLE
MS-Windows compatibility

### PR DESCRIPTION
**Pull request by mdboom**
Cc: @nden

### CODE REVIEW

**Comment by nden** [comment]
When compiling this branch I get now this error:

```
C:\Anaconda\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -IC:\Anaconda\lib\site-packages\numpy\core\include -Ispherical_geo
metry\..\cextern\qd-library\include -Ispherical_geometry\src -IC:\Anaconda\include -IC:\Anaconda\PC -c spherical_geometr
y\..\cextern\qd-library\src\util.cpp -o build\temp.win-amd64-2.7\Release\spherical_geometry\..\cextern\qd-library\src\ut
il.o
writing build\temp.win-amd64-2.7\Release\spherical_geometry\src\math_util.def
C:\Anaconda\Scripts\g++.bat -DMS_WIN64 -shared -s build\temp.win-amd64-2.7\Release\spherical_geometry\src\math_util.o bu
ild\temp.win-amd64-2.7\Release\spherical_geometry\..\cextern\qd-library\src\bits.o build\temp.win-amd64-2.7\Release\sphe
rical_geometry\..\cextern\qd-library\src\c_dd.o build\temp.win-amd64-2.7\Release\spherical_geometry\..\cextern\qd-librar
y\src\dd_real.o build\temp.win-amd64-2.7\Release\spherical_geometry\..\cextern\qd-library\src\dd_const.o build\temp.win-
amd64-2.7\Release\spherical_geometry\..\cextern\qd-library\src\fpu.o build\temp.win-amd64-2.7\Release\spherical_geometry
\..\cextern\qd-library\src\util.o build\temp.win-amd64-2.7\Release\spherical_geometry\src\math_util.def -LC:\Anaconda\li
bs -LC:\Anaconda\PCbuild\amd64 -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\spherical_geometry\math_util.pyd
build\temp.win-amd64-2.7\Release\spherical_geometry\src\math_util.o:math_util.c:(.text+0x2aaf): undefined reference to `
_npy_signbit_d'
build\temp.win-amd64-2.7\Release\spherical_geometry\src\math_util.o:math_util.c:(.text+0x2c51): undefined reference to `
_npy_signbit_d'
build\temp.win-amd64-2.7\Release\spherical_geometry\src\math_util.o:math_util.c:(.text+0x2e06): undefined reference to `
_npy_signbit_d'
build\temp.win-amd64-2.7\Release\spherical_geometry\src\math_util.o:math_util.c:(.text+0x2fbb): undefined reference to `
_npy_signbit_d'
build\temp.win-amd64-2.7\Release\spherical_geometry\src\math_util.o:math_util.c:(.text+0x38df): undefined reference to `
_npy_signbit_d'
build\temp.win-amd64-2.7\Release\spherical_geometry\src\math_util.o:math_util.c:(.text+0x3a81): more undefined reference
s to `_npy_signbit_d' follow
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\Anaconda\\Scripts\\g++.bat' failed with exit status 1
```

**Comment by mdboom** [comment]
Hmm...  I think maybe you're using a different compiler than I was.  If you change the line:

```
#ifdef _MSC_VER
```

to

```
#if 1
```

does it work?

**Comment by nden** [comment]
Yes, this worked for me.

**Comment by nden** [comment]
```
C:\Users\Nadia\PIA\src\sphere [pia-win +0 ~1 -0]> gcc -v
Using built-in specs.
COLLECT_GCC=C:\Anaconda\Scripts\gcc.bat\..\..\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/anaconda/mingw/bin/../libexec/gcc/x86_64-w64-mingw32/4.7.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../build/gcc/src/configure --target=x86_64-w64-mingw32 --prefix=/c/bb/vista64-mingw32/mingw-x86-x
86_64/build/build/root --with-sysroot=/c/bb/vista64-mingw32/mingw-x86-x86_64/build/build/root --enable-languages=all,obj
-c++ --enable-fully-dynamic-string --disable-multilib
Thread model: win32
gcc version 4.7.0 20111220 (experimental) (GCC)
```

**Comment by mdboom** [comment]
Ah -- I was testing with MSVC.  But it looks like mingw probably needs this change as well.

**Comment by mdboom** [comment]
@nden: Does the attached work for you?  I think it's now detecting mingw correctly, but I haven't tested it...

**Comment by nden** [comment]
This works now. Thanks!

**Pull request merged**
