### PR TITLE
Fixed reference to images

### PR DESCRIPTION
**Pull request by astrofrog**

### CODE REVIEW

**Comment by mdboom** [comment]
This breaks the sphinx build because now the links are invalid in that context.  Whatever happens here should ideally work in both.

**Comment by astrofrog** [comment]
@mdboom - ah, I didn't realize this was used in Sphinx!

**Comment by astrofrog** [comment]
Can we just add symbolic links to the images instead?

**Comment by astrofrog** [comment]
Symbolic links don't work for some reason. I'll close this an open an issue to not forget about it.

**Pull request closed without merging**
